<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CONTRASEA_popIngresoUsuariotxtContrasena</name>
   <tag></tag>
   <elementGuidId>0b103a3e-7a29-40d4-b731-9ea502cb0e36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='popIngresoUsuario_txtContrasena_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#popIngresoUsuario_txtContrasena_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#popIngresoUsuario_txtContrasena_I</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b29e27bf-d89b-4213-a41c-1b2f6e8e4e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Glass dxeEditAreaSys dxh0</value>
      <webElementGuid>10bff853-2cf3-47dd-a31e-d94e4e29e2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popIngresoUsuario_txtContrasena_I</value>
      <webElementGuid>64d8515b-577c-4cdd-a128-0185393200bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>popIngresoUsuario$txtContrasena</value>
      <webElementGuid>9583cba7-5cc9-4baf-aab0-c1f873a50563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>ASPx.EGotFocus('popIngresoUsuario_txtContrasena')</value>
      <webElementGuid>3cac97e3-bae9-4b8e-82ae-1a5bb18df03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ASPx.ELostFocus('popIngresoUsuario_txtContrasena')</value>
      <webElementGuid>12d787b6-09a8-4a9d-88fd-1119c73244a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>9a63334b-690f-43b3-91cd-5c7b09fe8e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>f7df384a-c8cd-4ec8-b40f-841aa2e86280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popIngresoUsuario_txtContrasena_I&quot;)</value>
      <webElementGuid>caddb1a6-0573-4b29-a017-b94b0da19c95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='popIngresoUsuario_txtContrasena_I']</value>
      <webElementGuid>0b858f10-7fc7-42c4-bb96-3e72767a1133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='popIngresoUsuario_txtContrasena']/tbody/tr/td/input</value>
      <webElementGuid>9c8dc537-a99f-450b-b6c6-7e18b88e05e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>75cac760-1ef5-43a1-ad29-4b11e8715723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'popIngresoUsuario_txtContrasena_I' and @name = 'popIngresoUsuario$txtContrasena' and @type = 'password']</value>
      <webElementGuid>b0c24cc8-ab13-491a-9ea0-1f6c5cbefcbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
