<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_USUARIO_popIngresoUsuariotxtUsuario</name>
   <tag></tag>
   <elementGuidId>10ae5bf6-a190-49ee-bc36-ef76ab0374a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='popIngresoUsuario_txtUsuario_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#popIngresoUsuario_txtUsuario_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#popIngresoUsuario_txtUsuario_I</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e08f77bb-9f49-40a0-89c5-369baea79f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Glass dxeEditAreaSys dxh0</value>
      <webElementGuid>461d3350-ad7b-4fdb-a189-57a8652a9593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popIngresoUsuario_txtUsuario_I</value>
      <webElementGuid>0109ad99-c53b-4b97-8194-b453ee324e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>popIngresoUsuario$txtUsuario</value>
      <webElementGuid>993ed4f8-394a-44da-8cb6-73404012bfcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>ASPx.EGotFocus('popIngresoUsuario_txtUsuario')</value>
      <webElementGuid>86019b8d-40aa-4687-8853-749fd36dd2ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ASPx.ELostFocus('popIngresoUsuario_txtUsuario')</value>
      <webElementGuid>57c947bb-b804-4e2c-8d44-ff92a0a699b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a63b73d7-6e71-473b-8035-b668a5262b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>668cae6f-3051-4b1e-aabb-b11a3871a9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popIngresoUsuario_txtUsuario_I&quot;)</value>
      <webElementGuid>572a0008-0ccc-4fa4-8b5a-52609776c9e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='popIngresoUsuario_txtUsuario_I']</value>
      <webElementGuid>13d2eeda-5e50-4fb1-99e2-082f1fc32c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='popIngresoUsuario_txtUsuario']/tbody/tr/td/input</value>
      <webElementGuid>41656eb5-ee41-4862-8c3d-0ff9782112db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>fd37b24e-12bc-46da-9fec-4d40150fc742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'popIngresoUsuario_txtUsuario_I' and @name = 'popIngresoUsuario$txtUsuario' and @type = 'text']</value>
      <webElementGuid>da32c637-71d5-4f4a-a98a-b7798d787eb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
