<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_USUARIO</name>
   <tag></tag>
   <elementGuidId>f5b9e1b4-01f5-4c99-97ef-2939e5f5e874</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='popIngresoUsuario_lbUsuario0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#popIngresoUsuario_lbUsuario0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;USUARIO :&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1220d00c-4dec-4729-9f5d-55dbad1d9b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeBase_DevEx</value>
      <webElementGuid>f3c82a92-e50b-47c0-bb69-4497cdbd869d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popIngresoUsuario_lbUsuario0</value>
      <webElementGuid>db467b3f-9488-4903-b186-fa3935938a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>USUARIO :</value>
      <webElementGuid>d0ff4b79-9bb1-4dbe-b944-dd499688b25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popIngresoUsuario_lbUsuario0&quot;)</value>
      <webElementGuid>36e85ca6-8909-4387-ba3e-e4ab4340b99f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='popIngresoUsuario_lbUsuario0']</value>
      <webElementGuid>caf8e236-748c-4522-8b62-1cedddc56f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popIngresoUsuario_PWC-1']/table[2]/tbody/tr/td/span</value>
      <webElementGuid>bdd6c03c-cf77-4703-9380-b8ac4785fb65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONSULTA POPULAR 2024'])[2]/following::span[1]</value>
      <webElementGuid>508a8f9f-6b74-459f-9acb-3dca5b0e99d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INGRESO DE USUARIO'])[1]/following::span[2]</value>
      <webElementGuid>531e7168-3e88-43d6-8c7f-945355e97952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTRASEÑA :'])[1]/preceding::span[1]</value>
      <webElementGuid>c8aa7ad6-14cd-4687-9eb8-41f23f264397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[2]/preceding::span[2]</value>
      <webElementGuid>7d1d9e78-38c6-40e2-9945-19dbe8f22bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='USUARIO :']/parent::*</value>
      <webElementGuid>bc2b72b8-98d1-4fe6-91bf-f00a3cdd14fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table[2]/tbody/tr/td/span</value>
      <webElementGuid>a453a55b-b38e-4e69-8fa0-d5f7173655a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'popIngresoUsuario_lbUsuario0' and (text() = 'USUARIO :' or . = 'USUARIO :')]</value>
      <webElementGuid>83d795f4-8692-4a6a-a206-46ce8732450b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
