<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_10</name>
   <tag></tag>
   <elementGuidId>4c4d2329-c7c3-48ce-9d3c-9ffd2c3b436d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dx-cdb062ee-78ec-f773-c3d0-918d86da1a66']/div/dx-data-grid/div/div[10]/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>dx-data-grid >> internal:has-text=&quot;CÓDIGO PROCESONOMBRE PROCESO129ELECCIONES PRESIDENCIALES Y LEGISLATIVAS ANTICIPA&quot;i >> internal:label=&quot;Items per page: 10&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bc83fb2e-11dd-4d02-bbbc-1f2fc87d555b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-page-size</value>
      <webElementGuid>08ae926a-1e87-40d3-984b-eef23524b085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a7c0f7de-c769-40b2-85db-9b192b258a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0c0aa6ee-0cb8-42c4-884a-07aeea17d3b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Items per page: 10</value>
      <webElementGuid>779d431a-0fdc-497f-81e5-102e6af69fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>50babec5-f861-4c1a-a9a1-b9de0195d8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dx-cdb062ee-78ec-f773-c3d0-918d86da1a66&quot;)/div[@class=&quot;dx-template-wrapper&quot;]/dx-data-grid[@class=&quot;dx-widget dx-visibility-change-handler&quot;]/div[@class=&quot;dx-datagrid dx-gridbase-container dx-datagrid-borders&quot;]/div[@class=&quot;dx-widget dx-datagrid-pager dx-pager&quot;]/div[@class=&quot;dx-page-sizes&quot;]/div[@class=&quot;dx-page-size&quot;]</value>
      <webElementGuid>e917ebcb-91d3-4c45-8de9-2b0d4dcfe79c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dx-cdb062ee-78ec-f773-c3d0-918d86da1a66']/div/dx-data-grid/div/div[10]/div/div[3]</value>
      <webElementGuid>c0fbfc25-c210-4636-9cd8-25db32199401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Filter'])[2]/following::div[5]</value>
      <webElementGuid>9fb788e7-eeb3-49b6-8e95-211b8e09fd5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ELECCIONES GENERALES 2021'])[6]/following::div[17]</value>
      <webElementGuid>167dd673-02e0-4305-93e9-8427f8212d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page 1 of 2 (8 items)'])[1]/preceding::div[1]</value>
      <webElementGuid>3bbe6113-c5de-4708-9791-7824b5028e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/dx-data-grid/div/div[10]/div/div[3]</value>
      <webElementGuid>d7490c9a-893b-4003-843d-b0298ec408ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '10' or . = '10')]</value>
      <webElementGuid>7e91e4fd-7e65-4ef5-9c6f-51fcfeb7f501</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
