<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nuevo Mensaje_dx-dropdowneditor-icon</name>
   <tag></tag>
   <elementGuidId>f6c54129-c478-4814-99fe-1f4e372b8f5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//dx-form[@id='undefined']/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dx-dropdowneditor-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Select&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>27570467-44c3-47e3-bc0f-b2d1d2a8c89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-dropdowneditor-icon</value>
      <webElementGuid>5538eb45-7a5c-4883-b849-79e581dbe1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;undefined&quot;)/div[@class=&quot;dx-layout-manager dx-widget&quot;]/div[@class=&quot;dx-widget dx-collection dx-responsivebox-screen-undefined dx-responsivebox&quot;]/div[@class=&quot;dx-box-flex dx-box dx-widget dx-collection&quot;]/div[@class=&quot;dx-item dx-box-item&quot;]/div[@class=&quot;dx-item-content dx-box-item-content&quot;]/div[@class=&quot;dx-first-row dx-first-col dx-last-col dx-last-row dx-field-item dx-col-0 dx-field-item-optional dx-field-item-has-group&quot;]/div[@class=&quot;dx-field-item-content dx-field-item-content-location-right&quot;]/div[@class=&quot;dx-form-group dx-group-colcount-1&quot;]/div[@class=&quot;dx-form-group-content&quot;]/div[@class=&quot;dx-layout-manager dx-widget&quot;]/div[@class=&quot;dx-widget dx-collection dx-responsivebox-screen-undefined dx-responsivebox&quot;]/div[@class=&quot;dx-box-flex dx-box dx-widget dx-collection&quot;]/div[@class=&quot;dx-item dx-box-item&quot;]/div[@class=&quot;dx-item-content dx-box-item-content&quot;]/div[@class=&quot;dx-first-row dx-first-col dx-last-col dx-field-item dx-col-0 dx-field-item-required dx-flex-layout&quot;]/div[@class=&quot;dx-field-item-content dx-field-item-content-location-right&quot;]/div[@class=&quot;dx-show-invalid-badge dx-dropdownbox dx-textbox dx-texteditor dx-show-clear-button dx-dropdowneditor-button-visible dx-editor-outlined dx-texteditor-empty dx-widget dx-texteditor-with-label dx-dropdowneditor dx-dropdowneditor-field-clickable dx-validator dx-visibility-change-handler dx-state-active&quot;]/div[@class=&quot;dx-dropdowneditor-input-wrapper&quot;]/div[@class=&quot;dx-texteditor-container&quot;]/div[@class=&quot;dx-texteditor-buttons-container&quot;]/div[@class=&quot;dx-widget dx-button-mode-contained dx-button-normal dx-dropdowneditor-button&quot;]/div[@class=&quot;dx-button-content&quot;]/div[@class=&quot;dx-dropdowneditor-icon&quot;]</value>
      <webElementGuid>90abee08-2f19-4b71-adee-059104a4b374</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dx-form[@id='undefined']/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>c0a7be9a-4a60-4bbd-9336-86eaba055d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>c7f497b2-737f-4748-8ce7-f13abd8bf4db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
