<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ELECCIONES GENERALES 2017_dx-scrollable_6f1775</name>
   <tag></tag>
   <elementGuidId>d5e2778c-3931-4e72-9e0a-c1a1c1b85e2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dx-cdb062ee-78ec-f773-c3d0-918d86da1a66']/div/dx-data-grid/div/div[6]/div/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dx-scrollable-scrollbar.dx-widget.dx-scrollbar-horizontal.dx-scrollbar-hoverable.dx-state-hover > div.dx-scrollable-scroll > div.dx-scrollable-scroll-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.dx-template-wrapper > dx-data-grid > .dx-datagrid > .dx-datagrid-rowsview > .dx-scrollable-wrapper > .dx-scrollable-container > div:nth-child(2) > .dx-scrollable-scroll > .dx-scrollable-scroll-content</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>732509e0-9936-4e15-9b16-bda9420b36f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-scrollable-scroll-content</value>
      <webElementGuid>07afd0e9-3a00-467b-b760-0cba790b2d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dx-cdb062ee-78ec-f773-c3d0-918d86da1a66&quot;)/div[@class=&quot;dx-template-wrapper&quot;]/dx-data-grid[@class=&quot;dx-widget dx-visibility-change-handler&quot;]/div[@class=&quot;dx-datagrid dx-gridbase-container dx-datagrid-borders&quot;]/div[@class=&quot;dx-datagrid-rowsview dx-datagrid-nowrap dx-scrollable dx-visibility-change-handler dx-scrollable-both dx-scrollable-simulated&quot;]/div[@class=&quot;dx-scrollable-wrapper&quot;]/div[@class=&quot;dx-scrollable-container&quot;]/div[@class=&quot;dx-scrollable-scrollbar dx-widget dx-scrollbar-horizontal dx-scrollbar-hoverable dx-state-hover&quot;]/div[@class=&quot;dx-scrollable-scroll&quot;]/div[@class=&quot;dx-scrollable-scroll-content&quot;]</value>
      <webElementGuid>fcab299c-bba8-4909-9fe2-a31bede814af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dx-cdb062ee-78ec-f773-c3d0-918d86da1a66']/div/dx-data-grid/div/div[6]/div/div/div[2]/div/div</value>
      <webElementGuid>4cdb66ed-5a44-4cdf-86ad-a19be3193257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/dx-data-grid/div/div[6]/div/div/div[2]/div/div</value>
      <webElementGuid>d604c7c1-dc6d-40f8-9dcc-c36a750e5044</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
