<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Loading_notificacion</name>
   <tag></tag>
   <elementGuidId>705b0a49-553f-48db-8259-765f754c3e11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='dx_dx-85769c66-ccd8-ebec-f219-ee43638b328d_notificacion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dx_dx-85769c66-ccd8-ebec-f219-ee43638b328d_notificacion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Nuevo Mensaje a Desplegar&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1eac5a2d-874b-455a-b64b-19ce2f5753a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dx_dx-85769c66-ccd8-ebec-f219-ee43638b328d_notificacion</value>
      <webElementGuid>79c16daf-f160-4a39-9fbe-b4d46da3ff1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-texteditor-input</value>
      <webElementGuid>a08a1c05-4e13-4713-afa2-158feee7ab72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6ef31d94-597e-4a83-825e-c3ebe560ccec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>c14e53ca-f12a-43ed-93fa-c59d4932af54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>notificacion</value>
      <webElementGuid>5b5be232-792d-4a84-bf0b-ef7b8836ef87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7c7e8c8d-3ea8-44e9-89cd-34ab146dae12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>dx-texteditor-label-3b41a68b-51b0-cdcc-31bc-6c4e11559561</value>
      <webElementGuid>22ed4b2a-d61e-41c8-ae14-dbbd5df6de5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>bd2293ac-76f4-4b3a-a5d7-a099ceeb7498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b79ab754-b054-41ee-8885-acbd807694c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dx_dx-85769c66-ccd8-ebec-f219-ee43638b328d_notificacion&quot;)</value>
      <webElementGuid>76218643-be76-4906-9ea0-03f4c5d06323</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='dx_dx-85769c66-ccd8-ebec-f219-ee43638b328d_notificacion']</value>
      <webElementGuid>6acf16dd-d181-4074-940c-7271d1a23c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dx-form[@id='undefined']/div/div/div/div/div/div/div/div/div/div/div/div/div[7]/div/div/div/div/div/div/textarea</value>
      <webElementGuid>036d7c94-34f5-48b0-b66c-3846967fd967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>cc05b0ec-37d8-43e4-ab60-44a12024da1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'dx_dx-85769c66-ccd8-ebec-f219-ee43638b328d_notificacion' and @name = 'notificacion']</value>
      <webElementGuid>ae82a413-26a6-45af-9b9e-cba22c38755b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
